import { NodeServices } from "@effect/platform-node";
import { expect, layer } from "@effect/vitest";
import { Effect, FileSystem, Path } from "effect";
import { PromptProjectErrorReason } from "../src/project-error.ts";
import { check, generate, outputName } from "../src/project.ts";

const makeProject = (files: Readonly<Record<string, string>>) =>
  Effect.gen(function* () {
    const fs = yield* FileSystem.FileSystem;
    const path = yield* Path.Path;
    const root = yield* fs.makeTempDirectoryScoped();
    for (const [file, text] of Object.entries(files)) {
      yield* fs.makeDirectory(path.dirname(path.join(root, file)), { recursive: true });
      yield* fs.writeFileString(path.join(root, file), text);
    }
    return { fs, output: path.join(root, outputName), root };
  });

layer(NodeServices.layer)("prompt projects", (it) => {
  it.effect("reads prompts and partials from nested folders and writes one module", () =>
    Effect.gen(function* () {
      const { fs, output, root } = yield* makeProject({
        "invoice/extract.prompt.md": "{{> ../shared/rules.partial.md}}\n",
        "notes.md": "This file is not a prompt.",
        "shared/rules.partial.md": "Answer in JSON.\n",
      });

      const result = yield* generate({ root });
      const code = yield* fs.readFileString(output);

      expect(result.changed).toBe(true);
      expect(code).toContain("extract: Runtime.definePrompt(");
      expect(code).toContain("Answer in JSON.");
      expect(code).not.toContain("not a prompt");
    }),
  );

  it.effect("does not write the file again when nothing changed", () =>
    Effect.gen(function* () {
      const { root } = yield* makeProject({ "hello.prompt.md": "Hi\n" });

      yield* generate({ root });
      const second = yield* generate({ root });

      expect(second.changed).toBe(false);
    }),
  );

  it.effect("passes the check after generate and fails after a prompt changes", () =>
    Effect.gen(function* () {
      const { fs, root } = yield* makeProject({ "hello.prompt.md": "Hi\n" });

      yield* generate({ root });
      yield* check({ root });
      yield* fs.writeFileString(`${root}/hello.prompt.md`, "Bye\n");
      const error = yield* Effect.flip(check({ root }));

      expect(error).toMatchObject({ reason: PromptProjectErrorReason.Outdated });
      expect(error.message).toContain("out of date");
    }),
  );

  it.effect("fails the check when the generated file does not exist", () =>
    Effect.gen(function* () {
      const { root } = yield* makeProject({ "hello.prompt.md": "Hi\n" });

      const error = yield* Effect.flip(check({ root }));

      expect(error.message).toContain("does not exist");
    }),
  );

  it.effect("pipes the code through the format command with the output path", () =>
    Effect.gen(function* () {
      const { fs, output, root } = yield* makeProject({ "hello.prompt.md": "Hi\n" });

      yield* generate({ format: "sed s#@computis/effect-md#{file}#", root });
      const code = yield* fs.readFileString(output);

      expect(code).toContain(`generated by ${output}.`);
    }),
  );

  it.effect("keeps an output path with spaces and quoted words as one argument", () =>
    Effect.gen(function* () {
      const { fs, output, root } = yield* makeProject({ "my prompts/hello.prompt.md": "Hi\n" });
      const nested = { root: `${root}/my prompts` };

      yield* generate({ ...nested, format: `sed "s#generated by @computis/effect-md#at {file}#"` });
      const code = yield* fs.readFileString(output.replace(outputName, `my prompts/${outputName}`));

      expect(code).toContain(`at ${root}/my prompts/${outputName}.`);
    }),
  );

  it.effect("fails when the format command fails", () =>
    Effect.gen(function* () {
      const { root } = yield* makeProject({ "hello.prompt.md": "Hi\n" });

      const error = yield* Effect.flip(generate({ format: "false", root }));

      expect(error).toMatchObject({
        _tag: "PromptProjectError",
        reason: PromptProjectErrorReason.FormatFailed,
      });
    }),
  );

  it.effect("reports a compile error with the path of the prompt file", () =>
    Effect.gen(function* () {
      const { root } = yield* makeProject({ "hello.prompt.md": "Hi {{name}}\n" });

      const error = yield* Effect.flip(generate({ root }));

      expect(error.message).toContain(`${root}/hello.prompt.md:1:6`);
    }),
  );
});
