import type { Domain } from "./domain.ts";
import { IDENTIFIER } from "./identifiers.ts";
import { quote } from "./simple-type/emit.ts";

export interface Built {
  readonly attributes: readonly string[];
  readonly code: string;
  readonly complex: boolean;
}

export interface Declaration extends Built {
  readonly identifier: string;
}

export interface ModuleOptions {
  readonly domain?: Domain | undefined;
  readonly prefix?: string | undefined;
  readonly root: string;
  readonly runtime: string;
  readonly source: string;
}

const LINE_BREAKING = /[\p{Cc}\u2028\u2029]/gu;

const commentText = (text: string) => text.replaceAll(LINE_BREAKING, " ");

const renderStrings = (values: readonly string[]) => `[${values.map(quote).join(", ")}]`;

export const renderModule = (parts: {
  readonly declarations: Iterable<Declaration>;
  readonly domainImport: (Domain & { readonly local: string }) | undefined;
  readonly imports: ReadonlySet<string>;
  readonly notes: readonly string[];
  readonly options: ModuleOptions;
  readonly rootIdentifier: string;
  readonly rootType: Declaration;
  readonly targetNamespace: string;
  readonly usage: ReadonlyMap<string, number>;
}) => {
  const { domainImport, notes, options, rootIdentifier, rootType, targetNamespace, usage } = parts;
  const imports = new Set(parts.imports);
  const rootAttributes = (usage.get(rootType.identifier) ?? 0) === 0 ? rootType.attributes : [];
  const rootOptions = [
    ...(rootAttributes.length === 0 ? [] : [`attributes: ${renderStrings(rootAttributes)}`]),
    ...(targetNamespace === "" ? [] : [`namespace: ${quote(targetNamespace)}`]),
    ...(options.prefix === undefined ? [] : [`prefix: ${quote(options.prefix)}`]),
  ];
  const body = [...parts.declarations].map((declaration) => {
    if (declaration.attributes.length === 0 || (usage.get(declaration.identifier) ?? 0) === 0) {
      return `export const ${declaration.identifier} = ${declaration.code};`;
    }
    imports.add("element");
    return `export const ${declaration.identifier} = ${declaration.code}.pipe(element({ attributes: ${renderStrings(declaration.attributes)} }));`;
  });
  const rootArguments = [
    quote(options.root),
    ...(rootOptions.length === 0 ? [] : [`{ ${rootOptions.join(", ")} }`]),
  ];
  body.push(
    `export const ${rootIdentifier} = ${rootType.identifier}.pipe(root(${rootArguments.join(", ")}));`,
  );
  const header = [
    `// This file is generated by @computis/effect-xml from ${commentText(options.source)}. Do not edit it.`,
    "/* oxlint-disable sort-keys -- XML is sequence-typed: the Struct field order is the element order of the XSD. */",
    `import { Schema } from "effect";`,
    `import { ${[...imports].toSorted().join(", ")} } from ${quote(options.runtime)};`,
    ...(domainImport === undefined
      ? []
      : [
          `import { ${
            domainImport.export === domainImport.local
              ? domainImport.local
              : `${IDENTIFIER.test(domainImport.export) ? domainImport.export : quote(domainImport.export)} as ${domainImport.local}`
          } } from ${quote(domainImport.module)};`,
        ]),
    ...(notes.length === 0
      ? []
      : [
          "",
          "// These elements belong to other namespaces and are not part of the Schema: decode documents",
          '// that contain them with the decoder option unknownElements: "skip".',
          ...notes.map((note) => `// - ${commentText(note)}`),
        ]),
  ];
  return `${header.join("\n")}\n\n${body.join("\n\n")}\n`;
};
